# Generated by Django 4.2.7 on 2025-11-24 12:05

from django.db import migrations


def dedupe_candidates(apps, schema_editor):
    Candidate = apps.get_model('poll', 'Candidate')
    Vote = apps.get_model('poll', 'Vote')
    VoteCount = apps.get_model('poll', 'VoteCount')

    seen = {}
    for c in Candidate.objects.all().order_by('display_order', 'id'):
        key = ((c.name or '').strip(), (c.party or '').strip())
        if key not in seen:
            seen[key] = c
            continue
        primary = seen[key]
        # Reassign votes
        Vote.objects.filter(candidate_id=c.id).update(candidate_id=primary.id)
        # Merge vote counts
        try:
            dup_vc = VoteCount.objects.get(candidate_id=c.id)
        except VoteCount.DoesNotExist:
            dup_vc = None
        if dup_vc:
            primary_vc, created = VoteCount.objects.get_or_create(candidate_id=primary.id, defaults={
                'total_votes': 0,
                'actual_votes': 0,
                'boosted_votes': 0
            })
            primary_vc.total_votes += dup_vc.total_votes
            primary_vc.actual_votes += dup_vc.actual_votes
            primary_vc.boosted_votes += dup_vc.boosted_votes
            primary_vc.save()
            dup_vc.delete()
        # Delete duplicate candidate
        c.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(dedupe_candidates, reverse_code=migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name='candidate',
            unique_together={('name', 'party')},
        ),
    ]
