# Generated by Django 4.2.7 on 2025-11-25 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0003_sitesettings'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='vote',
            name='vote_index',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('ip_address', 'vote_index')},
        ),
    ]
